robot: 
    name: panda
    icub_base_T_robot_base: [[-1., 0., 0., 0.], [0., -1., 0., 0.], [0., 0., 1., 0.], [0., 0., 0., 1.]]
    icub_hand_T_robot_hand: [[0., 1., 0., 0.], [-1., 0., 0., 0.], [0., 0., 1., 0.0], [0., 0., 0., 1.]]

sq_model:
    object_class: default  # cylinder, box, sphere, default
    tol: 0.00001
    optimizer_points: 50
    random_sampling: True
    merge_model: True
    minimum_points: 50

sq_grasp:
    hand: right
    tol: 0.00001
    constr_tol: 0.0001
    max_superq: 1
    plane_table: [0.0, 0.0, 1.0, 0.03]  # check this
    displacement: [0.00, 0.00, 0.00]
    hand_sq: [0.03, 0.05, 0.03, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    # how to set the following bounds?
    bounds_right: [[-0.7, -0.2], [-0.5, 0.5], [-0.3, 1], [-3.14, 3.14], [-3.14, 3.14], [-3.14, 3.14]]
    bounds_left: [[-0.7, -0.2], [-0.5, 0.5], [-0.3, 1], [-3.14, 3.14], [-3.14, 3.14], [-3.14, 3.14]]
    # bounds_constr_right: [-10000, 0.0, -10000, 0.0, -10000, 0.0, 0.001, 10.0, 0.0, 1.0, 0.00001, 10.0, 0.00001,
    #                         10.0, 0.00001, 10.0],
    # bounds_constr_left: [-10000, 0.0, -10000, 0.0, -10000, 0.0, 0.01, 10.0, 0.0, 1.0, 0.00001, 10.0, 0.00001,
    #                        10.0, 0.00001, 10.0],


visualizer:
    x: 0
    y: 0
    width: 600
    height: 600
